version: '3.3'
services:
  traefik:
    image: "traefik:v2.3"
    container_name: "traefik"
    command:
     # - "--providers.consulcatalog.endpoint.address=consul:8500"
      - --log.level=DEBUG
      - --log.format=json
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.traefik.address=:8888
      - --entrypoints.entrypoint-whoami-ssl.address=:8443
      - --entrypoints.entrypoint-whoami.address=:8000
      - --entrypoints.entrypoint-nginx-test.address=:8080
      - --providers.providersThrottleDuration=2s
      - --providers.file.directory=/configuration/
      - --providers.file.watch=true
      - --metrics.prometheus=true
      - --entryPoints.metrics.address=:8082
      - --metrics.prometheus.entryPoint=metrics
    ports:
      - "8080:8080"
      - "8888:8888"
      - "8443:8443"
      - "8000:8000"
      - "8082:8082"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "${PWD}/configuration/:/configuration/"
    networks:
      - traefik_net
# ...
  whoami:
    # A container that exposes an API to show its IP address
    image: traefik/whoami
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.whoami.loadbalancer.server.port=80"

      - "traefik.http.routers.whoami.rule=Host(`localhost`)"
      - "traefik.http.routers.whoami.entrypoints=entrypoint-whoami"

      - "traefik.http.routers.whoami-ssl.entrypoints=entrypoint-whoami-ssl"
      - "traefik.http.routers.whoami-ssl.tls=${WHOAMI_SSL}"
      - "traefik.http.routers.whoami-ssl.rule=Host(`localhost`)"
      # - "traefik.http.middlewares.test-redirectscheme.redirectscheme.scheme=https"
      # - "traefik.http.middlewares.test-redirectscheme.redirectscheme.permanent=true"
      # - "traefik.http.middlewares.test-redirectscheme.redirectscheme.port=8443"
      - "traefik.http.middlewares.testHeader.headers.customrequestheaders.X-my-custom-header=piupiu"
      - traefik.http.routers.whoami-ssl.middlewares=testHeader@docker

      - "traefik.http.routers.whoami-no-ssl.rule=Host(`localhost`)"
      - "traefik.http.routers.whoami-no-ssl.entrypoints=entrypoint-whoami-ssl"
      - traefik.http.middlewares.redirect_https.redirectregex.regex=^http://(.*)
      - traefik.http.middlewares.redirect_https.redirectregex.replacement=https://$${1}
      - traefik.http.routers.whoami-no-ssl.middlewares=redirect_https
    networks:
      - traefik_net

  web-test1:
    image: fl64/nginx_test:0.0.7
    environment:
      - T1_BC=red
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx-test.rule=Host(`localhost`)"
      - "traefik.http.services.nginx-test.loadbalancer.server.port=8080"
      - "traefik.http.routers.nginx-test.entrypoints=entrypoint-nginx-test"
    networks:
      - traefik_net

  web-test2:
    image: fl64/nginx_test:0.0.7
    environment:
      - T1_BC=blue
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx-test.rule=Host(`localhost`)"
      - "traefik.http.services.nginx-test.loadbalancer.server.port=8080"
      - "traefik.http.routers.nginx-test.entrypoints=entrypoint-nginx-test"
    networks:
      - traefik_net

  web-test3:
    image: fl64/nginx_test:0.0.7
    environment:
      - T1_BC=green
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx-test.rule=Host(`localhost`)"
      - "traefik.http.services.nginx-test.loadbalancer.server.port=8080"
      - "traefik.http.routers.nginx-test.entrypoints=entrypoint-nginx-test"
    networks:
      - traefik_net

networks:
  traefik_net:
