[tls.stores]
  [tls.stores.default]
   [tls.stores.default.defaultCertificate]
     certFile = "/configuration/localhost.crt"
     keyFile = "/configuration/localhost.key"
# [tls.options]
#   [tls.options.default]
#     [tls.options.default.clientAuth]
#       # in PEM format. each file can contain multiple CAs.
#       caFiles = ["/configuration/bundle.crt"]
#       clientAuthType = "RequireAndVerifyClientCert"
